In [41]:
# RWalker Oct. 1 Chord Candy Prototype
import os
import glob
import numpy as np
import matplotlib.pyplot as plt
import math

In [8]:
# Chord Candy Dictionary Test
from nested_lookup import nested_lookup

print("-")
print("-")
# Creating an empty Dictionary
numToName = {'C': 
                {'C Major': {
                    606467: 'C Major Root Position', 
                    646760: 'C Major 1st Inversion', 
                    676064: 'C Major 2nd Inversion'},
                },
            'F':
                {'F Minor': {
                    656860: 'F Minor Root Position',
                    686065: 'F Minor 1st Inversion',
                    606568: 'F Minor 2nd Inversion',
                }}
            }  

nameToNum = {'C': 
                {'C Major': {
                    'C Major Root Position': 606467, 
                    'C Major 1st Inversion': 646772, 
                    'C Major 2nd Inversion': 677276},
                },
            'F':
                {'F Minor': {
                    'F Minor Root Position': 656872,
                    'F Minor 1st Inversion': 566065,
                    'F Minor 2nd Inversion': 606568,
                }}
            }  
#print("Empty Dictionary: ")
#print(chordDict['C']['C Major'][606467])
#choice = chordDict.get('C', {}).get('C Major', {}).get(606467)

print(nested_lookup('C Major', chordDict))

#print(choice)

-
-
[{606467: 'C Major Root Position', 646772: 'C Major 1st Inversion', 677276: 'C Major 2nd Inversion'}]


In [105]:
# Starting chord input: 
inputChord = 'C Major 2nd Inversion'
inputNum = nested_lookup(inputChord, nameToNum)
inputSplit = np.array(chordIntSplit(inputNum[0]))
# Print out MIDI numbers from user input
print(inputSplit)

[67 72 76]


In [101]:
# Splits a 6 digit triad input input into individual note values
def chordIntSplit (chordInt, interval=2):
    chordInt = str(chordInt)
    split = []
    for k in range(0, len(chordInt), interval):
        split.append(int(chordInt[k:k + interval]))
    return split


# Reverses chordIntSplit, will combine the individual note values back into a single integer
def chordIntCombine (input):
    combine = int(str(int(input[0])) + str(int(input[1])) + str(int(input[2])))
    return combine

In [110]:
destinationChord = 'F Minor'
destinationNums = nested_lookup(key = destinationChord, document = nameToNum, wild = True, with_keys= False)


for n in range(0, len(destinationNums)-1):
    # Split destination chord into separate note values for comparison
    destTest = np.array(chordIntSplit(destinationNums[n+1]))
    print(destTest)

    # Look at octave above and octave below
    upOct = destTest + 12
    print(upOct)
    downOct = destTest - 12
    print(downOct)

    # Magnitude array
    np.array

    



    
    

    



[65 68 72]
[77 80 84]
[53 56 60]
[56 60 65]
[68 72 77]
[44 48 53]
[60 65 68]
[72 77 80]
[48 53 56]


In [102]:
splitTest = np.array(chordIntSplit(655690))

print(splitTest)

[65 56 90]


In [109]:
inputSplit-destTest


array([7, 7, 8])