In [3]:
# RWalker Oct. 1 Chord Candy Prototype
import os
import glob
import numpy as np
import matplotlib.pyplot as plt
import math

In [6]:
# Chord Candy Dictionary Test
from nested_lookup import nested_lookup

print("-")
print("-")
# Creating an empty Dictionary
numToName = {'C': 
                {'C Major': {
                    606467: 'C Major Root Position', 
                    646760: 'C Major 1st Inversion', 
                    676064: 'C Major 2nd Inversion'},
                
                'C Minor': {
                    606367: 'C Minor Root Postition',
                    676063: 'C Minor 1st Inversion',
                    636760: 'C Minor 2nd Inversion'},

                'C Diminished': {
                    606366: 'C Diminished Root Position',
                    666063: 'C Diminished 1st Inversion',
                    636660: 'C Diminished 2nd Inversion'},

                'C Augmented': {
                    606468: 'C Augmented Root Position',
                    686064: 'C Augmented 1st Inversion',
                    646860: 'C Augmented 2nd Inversion'}
                },

            'C#/Db': 
                {'C#/Db Major': {
                    616568: 'C#/Db Major Root Position', 
                    686165: 'C#/Db Major 1st Inversion', 
                    656861: 'C#/Db Major 2nd Inversion'},
                
                'C#/Db Minor': {
                    616468: 'C#/Db Minor Root Postition',
                    686164: 'C#/Db Minor 1st Inversion',
                    646861: 'C#/Db Minor 2nd Inversion'},

                'C#/Db Diminished': {
                    616467: 'C#/Db Diminished Root Position',
                    676164: 'C#/Db Diminished 1st Inversion',
                    646761: 'C#/Db Diminished 2nd Inversion'},

                'C#/Db Augmented': {
                    616569: 'C#/Db Augmented Root Position',
                    696165: 'C#/Db Augmented 1st Inversion',
                    656961: 'C#/Db Augmented 2nd Inversion'}
                },

            'D': 
                {'D Major': {
                    626669: 'D Major Root Position', 
                    646772: 'D Major 1st Inversion', 
                    677276: 'D Major 2nd Inversion'},
                
                'D Minor': {
                    626569: 'D Minor Root Postition',
                    676063: 'D Minor 1st Inversion',
                    636760: 'D Minor 2nd Inversion'},

                'D Diminished': {
                    626568: 'D Diminished Root Position',
                    666063: 'D Diminished 1st Inversion',
                    636660: 'D Diminished 2nd Inversion'},

                'D Augmented': {
                    626670: 'D Augmented Root Position',
                    686064: 'D Augmented 1st Inversion',
                    646860: 'D Augmented 2nd Inversion'}
                },

            'D#/Db': 
                {'D#/Db Major': {
                    636770: 'D#/Db Major Root Position', 
                    646772: 'D#/Db Major 1st Inversion', 
                    677276: 'D#/Db Major 2nd Inversion'},
                
                'D#/Db Minor': {
                    636670: 'D#/Db Minor Root Postition',
                    676063: 'D#/Db Minor 1st Inversion',
                    636760: 'D#/Db Minor 2nd Inversion'},

                'D#/Db Diminished': {
                    636669: 'D#/Db Diminished Root Position',
                    666063: 'D#/Db Diminished 1st Inversion',
                    636660: 'D#/Db Diminished 2nd Inversion'},

                'D#/Db Augmented': {
                    636771: 'D#/Db Augmented Root Position',
                    686064: 'D#/Db Augmented 1st Inversion',
                    646860: 'D#/Db Augmented 2nd Inversion'}
                },

            'E': 
                {'E Major': {
                    646871: 'E Major Root Position', 
                    646772: 'E Major 1st Inversion', 
                    677276: 'E Major 2nd Inversion'},
                
                'E Minor': {
                    646771: 'E Minor Root Postition',
                    676063: 'E Minor 1st Inversion',
                    636760: 'E Minor 2nd Inversion'},

                'E Diminished': {
                    646770: 'E Diminished Root Position',
                    666063: 'E Diminished 1st Inversion',
                    636660: 'E Diminished 2nd Inversion'},

                'E Augmented': {
                    646860: 'E Augmented Root Position',
                    686064: 'E Augmented 1st Inversion',
                    646860: 'E Augmented 2nd Inversion'}
                },

            'F': 
                {'F Major': {
                    656960: 'F Major Root Position', 
                    646772: 'F Major 1st Inversion', 
                    677276: 'F Major 2nd Inversion'},
                
                'F Minor': {
                    656860: 'F Minor Root Postition',
                    676063: 'F Minor 1st Inversion',
                    636760: 'F Minor 2nd Inversion'},

                'F Diminished': {
                    656871: 'F Diminished Root Position',
                    666063: 'F Diminished 1st Inversion',
                    636660: 'F Diminished 2nd Inversion'},

                'F Augmented': {
                    656961: 'F Augmented Root Position',
                    686064: 'F Augmented 1st Inversion',
                    646860: 'F Augmented 2nd Inversion'}
                },

            'F#/Gb': 
                {'F#/Gb Major': {
                    667061: 'F#/Gb Major Root Position', 
                    646772: 'F#/Gb Major 1st Inversion', 
                    677276: 'F#/Gb Major 2nd Inversion'},
                
                'F#/Gb Minor': {
                    666961: 'F#/Gb Minor Root Postition',
                    676063: 'F#/Gb Minor 1st Inversion',
                    636760: 'F#/Gb Minor 2nd Inversion'},

                'F#/Gb Diminished': {
                    666960: 'F#/Gb Diminished Root Position',
                    666063: 'F#/Gb Diminished 1st Inversion',
                    636660: 'F#/Gb Diminished 2nd Inversion'},

                'F#/Gb Augmented': {
                    667062: 'F#/Gb Augmented Root Position',
                    686064: 'F#/Gb Augmented 1st Inversion',
                    646860: 'F#/Gb Augmented 2nd Inversion'}
                },

            'G': 
                {'G Major': {
                    677162: 'G Major Root Position', 
                    646772: 'G Major 1st Inversion', 
                    677276: 'G Major 2nd Inversion'},
                
                'G Minor': {
                    677062: 'G Minor Root Postition',
                    676063: 'G Minor 1st Inversion',
                    636760: 'G Minor 2nd Inversion'},

                'G Diminished': {
                    677061: 'G Diminished Root Position',
                    666063: 'G Diminished 1st Inversion',
                    636660: 'G Diminished 2nd Inversion'},

                'G Augmented': {
                    677163: 'G Augmented Root Position',
                    686064: 'G Augmented 1st Inversion',
                    646860: 'G Augmented 2nd Inversion'}
                },

            'G#/Ab': 
                {'G#/Ab Major': {
                    686063: 'G#/Ab Major Root Position', 
                    646772: 'G#/Ab Major 1st Inversion', 
                    677276: 'G#/Ab Major 2nd Inversion'},
                
                'G#/Ab Minor': {
                    687163: 'G#/Ab Minor Root Postition',
                    676063: 'G#/Ab Minor 1st Inversion',
                    636760: 'G#/Ab Minor 2nd Inversion'},

                'G#/Ab Diminished': {
                    687162: 'G#/Ab Diminished Root Position',
                    666063: 'G#/Ab Diminished 1st Inversion',
                    636660: 'G#/Ab Diminished 2nd Inversion'},

                'G#/Ab Augmented': {
                    686064: 'G#/Ab Augmented Root Position',
                    686064: 'G#/Ab Augmented 1st Inversion',
                    646860: 'G#/Ab Augmented 2nd Inversion'}
                },

            'A': 
                {'A Major': {
                    696164: 'A Major Root Position', 
                    646772: 'A Major 1st Inversion', 
                    677276: 'A Major 2nd Inversion'},
                
                'A Minor': {
                    696064: 'A Minor Root Postition',
                    676063: 'A Minor 1st Inversion',
                    636760: 'A Minor 2nd Inversion'},

                'A Diminished': {
                    696063: 'A Diminished Root Position',
                    666063: 'A Diminished 1st Inversion',
                    636660: 'A Diminished 2nd Inversion'},

                'A Augmented': {
                    696165: 'A Augmented Root Position',
                    686064: 'A Augmented 1st Inversion',
                    646860: 'A Augmented 2nd Inversion'}
                },

            'A#/Bb': 
                {'A#/Bb Major': {
                    706265: 'A#/Bb Major Root Position', 
                    646772: 'A#/Bb Major 1st Inversion', 
                    677276: 'A#/Bb Major 2nd Inversion'},
                
                'A#/Bb Minor': {
                    706165: 'A#/Bb Minor Root Postition',
                    676063: 'A#/Bb Minor 1st Inversion',
                    636760: 'A#/Bb Minor 2nd Inversion'},

                'A#/Bb Diminished': {
                    706164: 'A#/Bb Diminished Root Position',
                    666063: 'A#/Bb Diminished 1st Inversion',
                    636660: 'A#/Bb Diminished 2nd Inversion'},

                'A#/Bb Augmented': {
                    706266: 'A#/Bb Augmented Root Position',
                    686064: 'A#/Bb Augmented 1st Inversion',
                    646860: 'A#/Bb Augmented 2nd Inversion'}
                },

            'B': 
                {'B Major': {
                    716366: 'B Major Root Position', 
                    646772: 'B Major 1st Inversion', 
                    677276: 'B Major 2nd Inversion'},
                
                'B Minor': {
                    716266: 'B Minor Root Postition',
                    676063: 'B Minor 1st Inversion',
                    636760: 'B Minor 2nd Inversion'},

                'B Diminished': {
                    716265: 'B Diminished Root Position',
                    666063: 'B Diminished 1st Inversion',
                    636660: 'B Diminished 2nd Inversion'},

                'B Augmented': {
                    716367: 'B Augmented Root Position',
                    686064: 'B Augmented 1st Inversion',
                    646860: 'B Augmented 2nd Inversion'}
                },
            }  

nameToNum = {'C': 
                {'C Major': {
                    'C Major Root Position': 606467, 
                    'C Major 1st Inversion': 646772, 
                    'C Major 2nd Inversion': 677276},
                },
            'F':
                {'F Minor': {
                    'F Minor Root Position': 656872,
                    'F Minor 1st Inversion': 566065,
                    'F Minor 2nd Inversion': 606568,
                }}
            }  
#print("Empty Dictionary: ")
#print(chordDict['C']['C Major'][606467])
#choice = chordDict.get('C', {}).get('C Major', {}).get(606467)

#print(nested_lookup('C Major', nameToNum))

#print(choice)

-
-


In [7]:
# Splits a 6 digit triad input input into individual note values
def chordIntSplit (chordInt, interval=2):
    chordInt = str(chordInt)
    split = []
    for k in range(0, len(chordInt), interval):
        split.append(int(chordInt[k:k + interval]))
    return split


# Reverses chordIntSplit, will combine the individual note values back into a single integer
def chordIntCombine (input):
    combine = int(str(int(input[0])) + str(int(input[1])) + str(int(input[2])))
    return combine

In [8]:
# Starting chord input: 
inputChord = 'C Major Root Position'
inputNum = nested_lookup(inputChord, nameToNum)
inputSplit = np.array(chordIntSplit(inputNum[0]))
# Print out MIDI numbers from user input
print(inputSplit)

destinationChord = 'F Minor'
destinationNums = nested_lookup(key = destinationChord, document = nameToNum, wild = True, with_keys= False)


lookupArray = np.zeros(9)
magArray = np.zeros(9)
for n in range(0, len(destinationNums)-1):
    arrayIndex = n*3
    # Split destination chord into separate note values for comparison
    destTest = np.array(chordIntSplit(destinationNums[n+1]))
    lookupArray[arrayIndex] = chordIntCombine(destTest)
    magArray[arrayIndex] = np.sum(np.abs(destTest - inputSplit))
    #print(destTest)

    # Look at octave above and octave below
    upOct = destTest + 12
    lookupArray[arrayIndex+1] = chordIntCombine(upOct)
    magArray[arrayIndex+1] = np.sum(np.abs(upOct - inputSplit))
    #print(upOct)
    downOct = destTest - 12
    lookupArray[arrayIndex+2] = chordIntCombine(downOct)
    magArray[arrayIndex+2] = np.sum(np.abs(downOct - inputSplit))
    #print(downOct)



[60 64 67]


In [9]:
#print(lookupArray)
#print('----')
#print(magArray)
minVal = np.argmin(magArray)
destinationCalc = int(lookupArray[minVal])
splitStuff = np.array(chordIntSplit(destinationCalc))

normalize = (splitStuff%12) + 60

normalizeCombine = chordIntCombine(normalize)

print(splitStuff)
print(nested_lookup(normalizeCombine, numToName))

[60 65 68]
[]


In [10]:
normalize

array([60, 65, 68], dtype=int32)